# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:
      - main
      - release-**
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: test1
      run: echo hoge
      if: ( ${{ github.event_name != 'pull_request' }} )
