# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Print repo name
      run: echo ${{ github.repository }}

    - name: Print github_ref
      run: echo ${{ github.ref }}

    - name: Print github_base_ref
      run: echo ${{ github.base_ref }}

    - name: Print github_event
      run: echo ${{ github.event_name }}

    - name: Create json
      run: |
        echo '{ "myatt": "value1" }' > /tmp/report_with_metadata.json

    - name: Import into MongoDB
      run: |
        docker run --rm \
          -v /tmp/report_with_metadata.json:/tmp/report_with_metadata.json \
          mongo mongosh --host "mongodb+srv://mongo:${{ secrets.MONGO_PASS }}@tyk-ci.pzeexqy.mongodb.net" ${DATABASE_NAME} --eval 'db.test_report.insertOne(JSON.parse(cat("/tmp/report_with_metadata.json")))'
      env:
        DATABASE_NAME: test
        COLLECTION_NAME: test_report






