# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:
      - main
      - release-**
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Always echo
      run: echo "Always-retry"

    - name: test1
      run: echo "${{ github.event_name}}"
      if: github.event_name != 'pull_request'
