# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Multiline check
      run: |
        docker \
        ps

    - name: test1
      run: echo hoge
      if: ( 'a' == 'a' )

    - name: test2
      run: echo hoge
      if: ( 'a' == 'b' )

    - name: test3
      run: echo hoge
      if: >
        'a' == 'a'

    - name: test4
      run: echo hoge
      if: >
        'a' == 'b'

    - name: test5
      run: echo hoge
      if: >
        ${{ 'a' == 'a' }}

    - name: test6
      run: echo hoge
      if: >
        ${{ 'a' == 'b' }}
