name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*'
    
jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v3
          
      - name: CI env
        run:
          tar -cvzf my-env.tgz . || true