name: Retry

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  main:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2 

      # - name: Docker Build
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: false
      #     tags: app:latest

      - name: retry docker build
        uses: Wandalen/wretry.action@v1.0.20
        with:
          action: docker/build-push-action@v3
          attempt_limit: 3
          attempt_delay: 2000
