name: test-tag

on:
  pull_request:
    tags:
      - v*

jobs:
  test-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Parse major version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "MM_TAG=$( echo "${{ github.ref_name}}" | grep -o "[0-9].[0-9]")" >> GITHUB_ENV
          echo "This is the parsed tag $MM_TAG"
