name: Test Local Composite Action

on:
  workflow_call:
    inputs:
      some-action:
        type: string
        description: "An example composite action"
        required: true
        default: "my-composite-action"

jobs:
  test-local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run composite action
        uses: ./.github/actions/my-composite-action
        with:
          some-input: "${{ inputs.some-action }}"
